CREATE TABLE `listing` (  
	`listingID` int(11) NOT NULL AUTO_INCREMENT,
	`title` varchar(255) DEFAULT NULL,
	`url` varchar(255) DEFAULT NULL,
	`location` varchar(255) DEFAULT NULL,
	`yearMakeModel` varchar(255) DEFAULT NULL,
	`odometer` int(11) DEFAULT NULL,
	`vehicleCondition` varchar(255) DEFAULT NULL,
	`cylinders` varchar(255) DEFAULT NULL,
	`drive` varchar(255) DEFAULT NULL,
	`fuel` varchar(255) DEFAULT NULL,
	`color` varchar(255) DEFAULT NULL,
	`titleStatus` varchar(255) DEFAULT NULL,
	`size` varchar(255) DEFAULT NULL,
	`transmission` varchar(255) DEFAULT NULL,
	`vehicleType` varchar(255) DEFAULT NULL,
	`description` varchar(15000) DEFAULT NULL,
	`price` int(11) DEFAULT NULL,
	`postedDate` date DEFAULT NULL,
	`validateStatus` varchar(1) DEFAULT NULL,
	PRIMARY KEY (`listingID`),
	UNIQUE KEY `url` (`url`),
	KEY `fk_location` (`location`),
	FULLTEXT KEY `title_index` (`title`),
	CONSTRAINT `fk_location` FOREIGN KEY (`location`) REFERENCES `location` (`siteName`)
  )
